name: weatherkiosk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+1
  http: ^0.12.2
  intl: ^0.16.1
  flutter_screenutil: ^4.0.2+5
  sqflite: ^1.3.2+2
  path: ^1.7.0
  weather_icons: ^2.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/wk.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/wk.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Current & Forecast Icons 65 Pix
    - assets/images/65/clear-day.png
    - assets/images/65/clear-night.png
    - assets/images/65/cloudy.png
    - assets/images/65/fog.png
    - assets/images/65/partly-cloudy-day.png
    - assets/images/65/partly-cloudy-night.png
    - assets/images/65/rain.png
    - assets/images/65/snow.png
    - assets/images/65/thunderstorm.png
    - assets/images/65/wind.png
    - assets/images/65/na.png
    # Past Icons 30 Pix
    - assets/images/30/clear-day.png
    - assets/images/30/clear-night.png
    - assets/images/30/cloudy.png
    - assets/images/30/fog.png
    - assets/images/30/partly-cloudy-day.png
    - assets/images/30/partly-cloudy-night.png
    - assets/images/30/rain.png
    - assets/images/30/snow.png
    - assets/images/30/thunderstorm.png
    - assets/images/30/wind.png
    - assets/images/30/na.png
    # Background Images
    - assets/images/background/cloudyFall.jpg
    - assets/images/background/cloudyWinter.jpg
    - assets/images/background/cloudySpring.jpg
    - assets/images/background/cloudySummer.jpg
    - assets/images/background/sunnyFall.jpg
    - assets/images/background/sunnyWinter.jpg
    - assets/images/background/sunnySpring.jpg
    - assets/images/background/sunnySummer.jpg
    - assets/images/background/rainFall.jpg
    - assets/images/background/rainWinter.jpg
    - assets/images/background/rainSpring.jpg
    - assets/images/background/rainSummer.jpg
    - assets/images/background/night.jpg
    - assets/images/background/foggyFall.jpg
    - assets/images/background/foggyWinter.jpg
    - assets/images/background/foggySpring.jpg
    - assets/images/background/foggySummer.jpg
    - assets/images/background/snow.jpg
    - assets/images/background/thunderstorm.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-B.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
